github: [HTechMedia]
custom: ['https://www.paypal.me/NxtStark']
- name: Resize images
  uses: alexrogalskiy/github-action-image-resizer@master
  with:
    prefix: '<!--views:marker:start-->\n'
    suffix: '\n<!--views:marker:end-->'
    sourceFile: './data/info.md'
    placeholder: '<!--views:marker:start-->[\s\S]*?<!--views:marker:end-->'
    replacement: '<p align="center" style="text-align:center;">Data Block</p>'
